[package]
name = "fs-swap"
version = "0.2.6"
authors = ["debris <marek.kotewicz@gmail.com>", "Parity Technologies <admin@parity.io>"]
description = "Cross-platform implementation of path swap"
license = "MIT"
homepage = "https://github.com/paritytech/fs-swap"

[dependencies]
clap = { version = "4", features = ["derive"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.90"

[target.'cfg(target_os = "macos")'.dependencies]
libloading = "0.5"
lazy_static = "1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["ktmw32", "handleapi", "fileapi", "errhandlingapi", "winbase"] }

[dev-dependencies]
tempdir = "0.3"

[badges]
travis-ci = { repository = "debris/fs-swap", branch = "master"}
appveyor = { repository = "debris/fs-swap", branch = "master"}
